#!/usr/bin/env python3
import sys
import subprocess
import requests 
from datetime import datetime
import platform 

def main():
    if len(sys.argv) < 3 and (sys.argv[1] != "install" or sys.argv[1] != "update"):
        print("Usage: nscan install <package> || nscan update <package>")
        sys.exit(1)


    typeOfCommand = sys.argv[1]
    packageName = sys.argv[2]

    print(f"Scanning {packageName}...")
    print(f"Weekly downloads for {packageName}: {getWeeklyDownloads(packageName)}")
    print(f"Monthly downloads for {packageName}: {getMonthlyDownloads(packageName)}")
    print(f"Last update to {packageName} is: {getLastUpdate(packageName)}")

    if typeOfCommand == "install":
        continueInstallation = input("Are you sure you want to continue with the installation (y/n):").lower()
        while continueInstallation != "y" and continueInstallation != "n":
            continueInstallation = input("Are you sure you want to continue with the installation (y/n):").lower()

        # if continueInstallation == "y":
        #     installation = subprocess.run(["npm", "install", packageName])
        #     sys.exit(installation.returncode)
        # elif continueInstallation.lower() == "n":
        #     print("Aborting Installation")
        #     sys.exit()
        if continueInstallation == "y":
            npm_command = "npm.cmd" if platform.system() == "Windows" else "npm"
            installation = subprocess.run([npm_command, "install", packageName])
            sys.exit(installation.returncode)
        if continueUpdate == "y":
            npm_command = "npm.cmd" if platform.system() == "Windows" else "npm"
            update = subprocess.run([npm_command, typeOfCommand, packageName])
            sys.exit(update.returncode)
    else:
        continueUpdate = input("Are you sure you want to continue with the update (y/n):").lower()
        while continueUpdate != "y" and continueUpdate != "n":
            continueUpdate = input("Are you sure you want to continue with the update (y/n):").lower()

        if continueUpdate == "y":
            update = subprocess.run(["npm", typeOfCommand, packageName])
            sys.exit(update.returncode)
        elif continueUpdate.lower() == "n":
            print("Aborting Update")
            sys.exit() 


def getWeeklyDownloads(packageName : str):
    try:
        url = f" https://api.npmjs.org/downloads/point/last-week/{packageName}"
        response = requests.get(url)
        data = response.json()
        return data.get("downloads")
    except Exception as e:
        print(f"Error is {e}")
        return None
    
def getMonthlyDownloads(packageName : str):
    try:
        url = f" https://api.npmjs.org/downloads/point/last-month/{packageName}"
        response = requests.get(url)
        data = response.json()
        downloads = data.get("downloads")
        return downloads
    except Exception as e:
        print(f"Error is: {e}")
        return None

def getLastUpdate(packageName : str):
    try:
        url = f"https://registry.npmjs.org/{packageName}"
        response = requests.get(url)
        data = response.json()
        date = data["time"]["modified"]
        dt = datetime.fromisoformat(date.replace("Z", "+00:00"))
        return dt.strftime("%d-%m-%Y %H:%M:%S")
    except Exception as e:
        print(f"Error is {e}")
        return None

if __name__ == "__main__":
    main()
