#!/usr/bin/env python3
import sys
import subprocess

def main():
    if len(sys.argv) < 3 or sys.argv[1] != "install":
        print("Usage: nscan install <package>")
        sys.exit(1)

    packageName = sys.argv[2]

    print(f"Scanning {packageName}...")

    installation = subprocess.run(["npm", "install", packageName])

    sys.exit(installation.returncode)

if __name__ == "__main__":
    main()
