#!/usr/bin/env python3
import sys
import subprocess
import requests 
from datetime import datetime, timedelta
import platform 
from typosquatting import typosquattingDummyFunction
from databaseSetup import setupDatabase, addPackageToDatabase, getPackageInfo

def main():
    setupDatabase()
    addPackageToDatabase("lodash", getWeeklyDownloads("lodash"), getMonthlyDownloads("lodash"), getLastUpdate("lodash")) #DEBUG LINE TO MAKE SURE IT WORKS (CURRENTLY NOT WORKING)
    if len(sys.argv) < 3 and (sys.argv[1] != "install" or sys.argv[1] != "update"):
        print("Usage: nscan install <package> || nscan update <package>")
        sys.exit(1)


    typeOfCommand = sys.argv[1]
    packageName = sys.argv[2]

    weeklyDownloads = getWeeklyDownloads(packageName)
    monthlyDownloads = getMonthlyDownloads(packageName)
    lastUpdate = getLastUpdate(packageName)

    print(f"Scanning {packageName}...")

    downloadLowerBound = (weeklyDownloads * 4) * 0.9
    downloadUpperBound = (weeklyDownloads * 4) * 1.1

    def isPackageOutdated(lastUpdate : str):
        lastUpdateDate = datetime.strptime(lastUpdate, "%d-%m-%Y %H:%M:%S")
        sixMonthsAgo = datetime.now() - timedelta(days=6 * 30)
        return lastUpdateDate < sixMonthsAgo



    if (monthlyDownloads < downloadLowerBound) or (monthlyDownloads > downloadUpperBound) or (weeklyDownloads < 100000) or (monthlyDownloads < 1000000):
        print("WARNING: Package download information is suspicious")
        redText(f"Weekly downloads for {packageName}: {weeklyDownloads}")
        redText(f"Monthly downloads for {packageName}: {monthlyDownloads}")
        typosquattingDummyFunction()
    else:
        greenText(f"Weekly downloads for {packageName}: {weeklyDownloads}")
        greenText(f"Monthly downloads for {packageName}: {monthlyDownloads}")
    if (isPackageOutdated(lastUpdate)):
        print("WARNING: Package last update information is suspicious")
        redText(f"Last update to {packageName} is: {lastUpdate}")
        typosquattingDummyFunction()
    else:
        greenText(f"Last update to {packageName} is: {lastUpdate}")


    if typeOfCommand == "install":
        continueInstallation = input("Are you sure you want to continue with the installation (y/n):").lower()
        while continueInstallation != "y" and continueInstallation != "n":
            continueInstallation = input("Are you sure you want to continue with the installation (y/n):").lower()

        if continueInstallation == "y":
            npm_command = "npm.cmd" if platform.system() == "Windows" else "npm"
            installation = subprocess.run([npm_command, "install", packageName])
            sys.exit(installation.returncode)
        elif continueInstallation == "n":
            print(f"Aborting installation of {packageName}")
            sys.exit()
    else:
        continueUpdate = input("Are you sure you want to continue with the update (y/n):").lower()
        while continueUpdate != "y" and continueUpdate != "n":
            continueUpdate = input("Are you sure you want to continue with the update (y/n):").lower()

        if continueUpdate == "y":
            npm_command = "npm.cmd" if platform.system() == "Windows" else "npm"
            update = subprocess.run([npm_command, typeOfCommand, packageName])
            sys.exit(update.returncode)
        elif continueUpdate == "n":
            print(f"Aborting update of {packageName}")
            sys.exit()


def getWeeklyDownloads(packageName : str):
    try:
        url = f" https://api.npmjs.org/downloads/point/last-week/{packageName}"
        response = requests.get(url)
        data = response.json()
        return data.get("downloads")
    except Exception as e:
        print(f"Error is {e}")
        return None
    
def getMonthlyDownloads(packageName : str):
    try:
        url = f" https://api.npmjs.org/downloads/point/last-month/{packageName}"
        response = requests.get(url)
        data = response.json()
        downloads = data.get("downloads")
        return downloads
    except Exception as e:
        print(f"Error is: {e}")
        return None

def getLastUpdate(packageName : str):
    try:
        url = f"https://registry.npmjs.org/{packageName}"
        response = requests.get(url)
        data = response.json()
        date = data["time"]["modified"]
        dt = datetime.fromisoformat(date.replace("Z", "+00:00"))
        return dt.strftime("%d-%m-%Y %H:%M:%S")
    except Exception as e:
        print(f"Error is {e}")
        return None
    
def redText(text):
    print(f"\033[31m{text}\033[0m")

def greenText(text):
    print(f"\033[32m{text}\033[0m")

if __name__ == "__main__":
    main()
